imports:
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/config.yml" }
    - {
          resource: "@SyliusShopApiPlugin/Resources/config/app/sylius_mailer.yml",
      }

fos_rest:
    exception: true
    view:
        formats:
            json: true
            xml: true
        empty_content: 204
    format_listener:
        rules:
            - {
                  path: "^/shop-api",
                  priorities: ["json"],
                  fallback_format: json,
                  prefer_extension: true,
              }
            - {
                  path: "^/api/.*",
                  priorities: ["json", "xml"],
                  fallback_format: json,
                  prefer_extension: true,
              }
            - { path: "^/", stop: true }
